import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ParcelChat from "@/components/ParcelChat/ParcelChat";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nigerian Diaspora E-Commerce Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <ParcelChat />
      </body>
    </html>
  );
}
