import "./globals.css";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import ParcelChat from "@/components/ParcelChat/ParcelChat";

/* ================================
   SATOSHI (PRIMARY UI FONT)
================================ */
const satoshi = localFont({
  src: [
    { path: "../../public/fonts/Satoshi-Light.woff2", weight: "300" },
    { path: "../../public/fonts/Satoshi-Regular.woff2", weight: "400" },
    { path: "../../public/fonts/Satoshi-Medium.woff2", weight: "500" },
    { path: "../../public/fonts/Satoshi-Bold.woff2", weight: "700" },
    { path: "../../public/fonts/Satoshi-Black.woff2", weight: "900" },
  ],
  variable: "--font-satoshi",
  display: "swap",
});

/* ================================
   GEIST MONO (CODE / TECH TEXT)
================================ */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* ================================
   METADATA
================================ */
export const metadata = {
  title: "Nigerian Diaspora E-Commerce Platform",
  description: "Generated by create next app",
};

/* ================================
   ROOT LAYOUT
================================ */
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={satoshi.variable}>
      <body className={geistMono.variable}>
        {children}
        <ParcelChat />
      </body>
    </html>
  );
}
